package cn.mcxyd.xiyuanmarry.service;
import cn.mcxyd.xiyuanmarry.config.*;import cn.mcxyd.xiyuanmarry.model.*;import cn.mcxyd.xiyuanmarry.repository.*;import cn.mcxyd.xiyuanmarry.scheduler.*;
import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import static cn.mcxyd.xiyuanmarry.service.RuleViolation.require;
/** 场地只保存坐标DTO；玩家传送分别进入实体调度器，回调绝不等待其他Region。 */
public final class WeddingService {
 private record Participant(UUID live,UUID id,PlayerSnapshot.Point point){}
 private record Ceremony(MarriageRecord marriage,List<Participant> people,UUID generation){}
 private final MarriageService marriages;private final ConfigurationManager config;private final UnifiedScheduler scheduler;private final WeddingCeremony vows=new WeddingCeremony();private final Map<String,Ceremony> active=new ConcurrentHashMap<>();private final Set<UUID> pendingChat=ConcurrentHashMap.newKeySet();private final Map<String,TaskHandle> timeouts=new ConcurrentHashMap<>();
 private final WeddingInvitationService invitations;
 public WeddingService(MarriageService m,ConfigurationManager c,UnifiedScheduler s){marriages=m;config=c;scheduler=s;invitations=new WeddingInvitationService(m,active::containsKey);}
 public String oathText(){return config.config().getString("wedding.oath-text","我愿意");}
 public WeddingPlan plan(MarriageRepository r,String id){String raw=r.get("weddings",id);return raw==null?WeddingPlan.empty():marriages.json().fromJson(raw,WeddingPlan.class);}
 private void save(MarriageRepository r,String id,WeddingPlan p){r.put("weddings",id,marriages.json().toJson(p));}
 private MarriageRecord engagement(MarriageRepository r,UUID id){var m=r.findByPlayer(id);require(m!=null&&m.state()==MarriageState.ENGAGED&&m.type().equals("WEDDING"),"wedding-required");return m;}
 public void setPoint(PlayerSnapshot actor,String role){require(Set.of("location","nx","nl","ly").contains(role)||validSeat(role),"invalid-argument");marriages.submit(actor.liveId(),r->{var m=engagement(r,actor.id());require(!active.containsKey(m.id()),"wedding-running");save(r,m.id(),plan(r,m.id()).point(role,actor.point()));return null;},x->marriages.notifyLive(actor.liveId(),"wedding-point-set","role",role));}
 private boolean validSeat(String role){try{int n=Integer.parseInt(role);return n>=1&&n<=1000;}catch(NumberFormatException e){return false;}}
 public void invite(PlayerSnapshot actor,PlayerSnapshot guest){require(guest!=null,"offline");marriages.submit(actor.liveId(),r->{var m=engagement(r,actor.id());require(!m.contains(guest.id()),"invalid-argument");require(!active.containsKey(m.id()),"wedding-running");save(r,m.id(),plan(r,m.id()).invite(guest.id(),new WeddingPlan.Invite(false,System.currentTimeMillis()+marriages.setting("wedding.invite-expire-hours",24)*3600000)));return null;},x->{marriages.notifyLive(actor.liveId(),"invite-sent");marriages.notifyLive(guest.liveId(),"invited","player",actor.name());});}
 public void respond(PlayerSnapshot guest,boolean accept){invitations.respond(guest,null,accept);}
 public void respond(PlayerSnapshot guest,String weddingId,boolean accept){invitations.respond(guest,weddingId,accept);}
 public List<WeddingInvitationService.Invitation> pendingInvitations(MarriageRepository repository,UUID guest){return invitations.pending(repository,guest);}
 public void start(PlayerSnapshot actor){marriages.submit(actor.liveId(),r->{require(config.config().getBoolean("wedding.enabled",true),"feature-unavailable");var m=engagement(r,actor.id());require(!active.containsKey(m.id()),"wedding-running");var p=plan(r,m.id());require(p.points().keySet().containsAll(Set.of("location","nx","nl","ly")),"wedding-location-required");var first=marriages.directory().identity(m.playerOne());var second=marriages.directory().identity(m.playerTwo());require(first!=null&&second!=null,"offline");var people=new ArrayList<Participant>();people.add(new Participant(first.liveId(),first.id(),p.points().get("nx")));people.add(new Participant(second.liveId(),second.id(),p.points().get("nl")));List<PlayerSnapshot.Point> seats=p.points().entrySet().stream().filter(e->validSeat(e.getKey())).sorted(Comparator.comparingInt(e->Integer.parseInt(e.getKey()))).map(Map.Entry::getValue).toList();int seat=0;for(var e:p.invites().entrySet()){var guest=marriages.directory().identity(e.getKey());if(guest!=null&&e.getValue().accepted()&&e.getValue().expires()>System.currentTimeMillis()){require(seat<seats.size(),"wedding-location-required");people.add(new Participant(guest.liveId(),guest.id(),seats.get(seat++)));}}return new Ceremony(m,List.copyOf(people),config.snapshot().generation());},this::teleport);}
 private void teleport(Ceremony c){String id=c.marriage().id();if(active.putIfAbsent(id,c)!=null)return;long seconds=marriages.setting("wedding.ceremony-timeout-seconds",300);timeouts.put(id,scheduler.runGlobalLater(()->stop(id,true),Math.max(1,seconds)*20));var remaining=new AtomicInteger(c.people().size());var failed=new AtomicBoolean();for(var target:c.people())scheduler.player(target.live(),player->{if(!active.containsKey(id))return;var point=target.point();scheduler.teleportAsync(player,point.world(),point.x(),point.y(),point.z(),point.yaw(),point.pitch()).whenComplete((success,error)->{if(error!=null||!Boolean.TRUE.equals(success))failed.set(true);if(remaining.decrementAndGet()==0){if(failed.get()||!c.generation().equals(config.snapshot().generation())){stop(id,true);return;}if(!active.containsKey(id))return;vows.start(c.marriage().playerOne(),c.marriage().playerTwo(),System.currentTimeMillis()+seconds*1000);for(var p:c.people())if(c.marriage().contains(p.id())){pendingChat.add(p.live());marriages.notifyLive(p.live(),"oath-prompt","oath",config.config().getString("wedding.oath-text","我愿意"));}}});});}
 public boolean pending(UUID live){return pendingChat.contains(live);}
 public void oathFromChat(UUID live) {
  if (!pending(live)) return;
  scheduler.player(live, player -> {
   var snapshot = marriages.directory().capture(player);
   oath(snapshot);
  });
 }
 public void oath(PlayerSnapshot actor){var m=marriages.view().byPlayer().get(actor.id());if(m==null||!active.containsKey(m.id())){marriages.notifyLive(actor.liveId(),"oath-missing");return;}var c=active.get(m.id());var target=c.people().stream().filter(p->p.id().equals(actor.id())).findFirst().orElse(null);if(target==null||!actor.point().near(target.point(),5)){stop(m.id(),true);return;}var result=vows.confirm(actor.id(),System.currentTimeMillis());if(result==WeddingCeremony.Result.COMPLETE){stop(m.id(),false);marriages.completeWedding(m.playerOne(),m.playerTwo());}else if(result==WeddingCeremony.Result.WAITING)marriages.notifyLive(actor.liveId(),"oath-waiting");else marriages.notifyLive(actor.liveId(),"oath-missing");}
 public void leave(UUID live){for(var e:active.entrySet())if(e.getValue().people().stream().anyMatch(p->p.live().equals(live)))stop(e.getKey(),true);pendingChat.remove(live);}
 private void stop(String id,boolean error){var c=active.remove(id);var timer=timeouts.remove(id);if(timer!=null)timer.cancel();if(c!=null){vows.cancel(c.marriage().playerOne());for(var p:c.people()){pendingChat.remove(p.live());if(error&&c.marriage().contains(p.id()))marriages.notifyLive(p.live(),"teleport-failed");}}}
 public void clear(){for(String id:List.copyOf(active.keySet()))stop(id,false);vows.clear();pendingChat.clear();}
}

