package cn.mcxyd.xiyuanmarry.config;
import cn.mcxyd.xiyuanmarry.gui.GuiLayout;import cn.mcxyd.xiyuanmarry.repository.DatabaseSettings;
import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.ZoneId;import java.util.*;
/** 磁盘读取只由IO工作队列调用；所有文件验证成功后，单次volatile写入发布新代次。 */
public final class ConfigurationManager {
 public static final List<String> GUI_NAMES=List.of("main_menu","propose","partner_info","wedding_plan","invitation","send_invite","gift","task","rank");
 public record Snapshot(UUID generation,Map<String,YamlConfiguration> files,Map<String,GuiLayout> menus,DatabaseSettings database,TaskCatalog tasks){public Snapshot{files=Map.copyOf(files);menus=Map.copyOf(menus);}}
 private final JavaPlugin plugin;private volatile Snapshot current;
 public ConfigurationManager(JavaPlugin p){plugin=p;}
 public void warn(String message){plugin.getLogger().warning(message);}
 public Snapshot prepare()throws Exception{var files=new HashMap<String,YamlConfiguration>();var names=new ArrayList<>(List.of("config.yml","messages.yml","tasks.yml","rank.yml","rewards.yml","weddings.yml"));for(String g:GUI_NAMES)names.add("gui/"+g+".yml");for(String name:names){Path file=plugin.getDataFolder().toPath().resolve(name);Files.createDirectories(file.getParent());YamlConfiguration defaults=new YamlConfiguration();try(var stream=plugin.getResource(name)){if(stream==null)throw new IllegalStateException("缺少默认资源 "+name);defaults.load(new InputStreamReader(stream,StandardCharsets.UTF_8));}if(!Files.exists(file))try(var stream=plugin.getResource(name)){Files.copy(Objects.requireNonNull(stream),file);}var y=new YamlConfiguration();y.load(file.toFile());boolean changed=ConfigurationDefaults.merge(y,defaults,name);files.put(name,y);if(changed)y.save(file.toFile());}
  var c=files.get("config.yml");validate(c,files.get("messages.yml"));var menus=new HashMap<String,GuiLayout>();for(String g:GUI_NAMES)menus.put(g,GuiLayout.parse(files.get("gui/"+g+".yml"),org.bukkit.Material::isItem));var tasks=TaskCatalog.parse(files.get("tasks.yml"),c.getLong("bond.task-complete",20));if(files.get("rank.yml").getInt("top-size",10)<1||files.get("rank.yml").getInt("top-size",10)>1000)throw new IllegalArgumentException("排行榜数量范围1-1000");RewardCatalog.parse(files.get("rewards.yml"),c);if(!tasks.deferredTypes().isEmpty())warn("以下任务类型尚未启用，不进入每日循环："+tasks.deferredTypes());String type=c.getString("database.type","SQLITE").toUpperCase(Locale.ROOT);Path data=plugin.getDataFolder().toPath().toAbsolutePath().normalize();Path path=data.resolve(c.getString("database.sqlite-file","data/marriages.db")).normalize();if(!path.startsWith(data))throw new IllegalArgumentException("SQLite路径必须位于插件目录");var db=new DatabaseSettings(type,path,c.getString("database.mysql.host","127.0.0.1"),c.getInt("database.mysql.port",3306),c.getString("database.mysql.database","xiyuan_marry"),c.getString("database.mysql.username","marry"),c.getString("database.mysql.password",""),c.getString("database.mysql.parameters",""),c.getInt("database.pool-size",4),c.getLong("database.timeout-ms",5000));return new Snapshot(UUID.randomUUID(),files,menus,db,tasks);
 }
 public static void validate(YamlConfiguration c,YamlConfiguration m){String mode=c.getString("identity.mode","");if(!Set.of("OFFLINE_NAME","ONLINE_UUID").contains(mode))throw new IllegalArgumentException("非法身份模式");if(!m.isList("help")||m.getString("prefix","").isBlank())throw new IllegalArgumentException("语言文件help必须为列表，prefix不得为空");if(!c.isBoolean("bond.common-online-enabled"))throw new IllegalArgumentException("共同在线开关必须为布尔值");range(c,"bond.common-online-per-hour",0,1000000);range(c,"bond.first-together-login",0,1000000);range(c,"privileges.partner-teleport-cooldown-seconds",0,86400);rangeDouble(c,"privileges.buff-distance",0,1000);range(c,"privileges.ring-buff-duration-ticks",1,12000);range(c,"privileges.ring-effects.speed-amplifier",0,255);range(c,"privileges.ring-effects.resistance-amplifier",0,255);ZoneId.of(c.getString("timezone","Asia/Shanghai"));for(String k:List.of("engagement-hours","divorce-cooling-hours"))range(c,"marriage."+k,1,8760);range(c,"marriage.remarriage-cooling-hours",0,8760);range(c,"marriage.proposal-daily-limit",1,1000);range(c,"marriage.minimum-online-minutes",0,1000000);range(c,"marriage.proposal-expire-seconds",1,86400);long prior=-1;for(int i=1;i<=10;i++){long n=c.getLong("bond.levels."+i+".required",-1);if(n<=prior||i==1&&n!=0)throw new IllegalArgumentException("羁绊阈值必须从0严格递增");prior=n;}}
 private static void range(YamlConfiguration c,String key,long min,long max){if(!c.isInt(key)&&!c.isLong(key))throw new IllegalArgumentException("配置必须是整数: "+key);long n=c.getLong(key);if(n<min||n>max)throw new IllegalArgumentException("配置超出范围: "+key);}
 private static void rangeDouble(YamlConfiguration c,String key,double min,double max){if(!c.isDouble(key)&&!c.isInt(key)&&!c.isLong(key))throw new IllegalArgumentException("配置必须是数字: "+key);double n=c.getDouble(key);if(!Double.isFinite(n)||n<min||n>max)throw new IllegalArgumentException("配置超出范围: "+key);}
 public void publish(Snapshot next){current=next;}public Snapshot snapshot(){return Objects.requireNonNull(current,"配置尚未加载");}public YamlConfiguration config(){return snapshot().files().get("config.yml");}public YamlConfiguration messages(){return snapshot().files().get("messages.yml");}public YamlConfiguration file(String name){return snapshot().files().get(name);}public void load(){try{publish(prepare());}catch(Exception e){throw new IllegalStateException("配置加载失败",e);}}public void reload(){load();}
}

